INC-14 feat: add radio-group
internshipsamyrai44/components-lib pull request #9
Opened 2024-09-17 08:56 UTC by veluat

Added RadioGroup Component and Stories

2024-09-21 16:39 UTC, Vlad78 commented on src/components/radio-group/RadioGroup.tsx
> +import { Circle } from 'lucide-react'
Мы не используем lucide-react, файлы картинок лежат в макете во вкладке icons

2024-09-21 16:40 UTC, Vlad78 commented
У тебя в компоненте есть пакеты, которые нужно установить, но они не установлены

2024-09-21 16:42 UTC, Vlad78 commented
Еще сам package.json старой версии, я его обновил, тебе нужно подтянуть обновления из ветки dev

2024-09-22 11:55 UTC, veluat commented on src/components/radio-group/RadioGroup.tsx
> +import { Circle } from 'lucide-react'
Исправила.

2024-10-14 11:57 UTC, artvrybin commented
Линтер  и преттир не подключены. 
![image](https://github.com/user-attachments/assets/f9fd86f6-0c06-42a9-8cf8-b3342d3f356b)

2024-10-14 12:45 UTC, catobazz commented
стили на фокус не срабатывают, выделяется дефолтным 
![image](https://github.com/user-attachments/assets/3be5be03-ce1a-4da0-b8db-b608876d81f5)

2024-10-15 06:21 UTC, catobazz requested changes

2024-10-15 06:21 UTC, catobazz commented on src/components/radio-group/RadioGroup.tsx
> +            'flex items-center justify-center h-[20px] w-[20px] rounded-full border-2 border-light-100 bg-transparent',
на item надо добавить focus ( убрать дефолнтый бордер, добавить бордер, задать цвет )

2024-10-18 10:23 UTC, catobazz approved these changes

2024-10-18 10:26 UTC, fanur56 approved these changes

2024-10-26 19:19 UTC, merged